### ISSUE TITLE
联系邮箱提示邮箱账号不存在

### ISSUE THREAD

**Issue by shazi4399** [qxzhou1010/mpc_learn#1]
老师你好，我有个问题想请教下。但是发现你留的联系邮箱，好像有点问题。
提示收件人不存在。

<img width="443" alt="image" src="https://user-images.githubusercontent.com/25169930/194991111-1a03d5af-2fe6-443a-ba3f-970bb7f007f7.png">

**Comment by qxzhou1010** [comment]
抱歉，更正了邮箱，qixian.zhou@foxmail.com
